# syntax=docker/dockerfile:1.4
FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

# Crea una cartella di lavoro
RUN mkdir /workspace
WORKDIR /workspace

RUN apt-get update && apt-get install -y python3.10 python3-pip

# Copia i requirements
COPY requirements.txt .
RUN pip3 install --upgrade pip && pip3 install -r requirements.txt

# Installa librerie di sistema per immagini/video (opencv, matplotlib, ecc.)
RUN apt-get update && apt-get install -y ffmpeg libsm6 libxext6

# Installa jupyter e jupyter nbconvert per eseguire notebook da riga di comando
RUN pip install notebook nbconvert

# Espone una porta utile per debug, se necessario
EXPOSE 8888

# Nessun comando automatico: si lavora in modo interattivo
CMD ["/bin/bash"]